### PR TITLE
Fix: Correct typo for Preview Scene action

### PR DESCRIPTION
**Pull request by bryce-seifert**
Closes https://github.com/bitfocus/companion-module-obs-studio/issues/200

### CODE REVIEW

**Comment by IceCubeNinJah** [comment]
thank you, but how do I download it and instal ? I appreciate the info on GitHub as I havent been using very long.
Or do I get a new mod from the bitfocus site?

**Comment by bryce-seifert** [comment]
@IceCubeNinJah It will be a moment before a downloadable release is ready, as this change has to get merged with the Companion app as a whole. But when it does it will be available on the Bitfocus site, I can let you know when available to download

**Comment by IceCubeNinJah** [comment]
wow thanks for the quick response. That would be appreciated to know when it's ready. I also dont mind installing a config or json file, if i just new the steps. This is a really cool site but i can never really find the .dmg files or .zip.
Im a good AV tech but not a developer. Thanks!

**Comment by bryce-seifert** [comment]
@IceCubeNinJah The downloadable build with this fix is now available under the "beta" section at [Bitfocus.io](https://user.bitfocus.io/download)

**Comment by IceCubeNinJah** [comment]
Thank you so much. Kudos dood !

**Pull request merged**
