### PR TITLE
Fix constant error state bug; initialize dormant variables

### PR DESCRIPTION
**Pull request by bryce-seifert**

### CODE REVIEW

**Comment by GDSteelers** [comment]
I'm still having the constant "Connect/Disconnect" flickering between OBS and Companion. 

I know this is an old post, but is there a fix for this with the newest software? (Companion 2.3.1 & OBS 27.2.4 (64 bit)?

**Comment by bryce-seifert** [comment]
@GDSteelers this is a very old commit, since this the module has been completely rewritten for OBS 28 and obs-websocket 5.0.

To try out the latest version, you will need to use the [beta version of Companion](https://bitfocus.io/companion/download/builds/) and OBS 28 which comes pre installed with the new version of obs-websocket.

Let me know if you have any issues with that version!

**Comment by GDSteelers** [comment]
I'm trying to use this with Companion on my Pi 4b. I'll have to see if there is a way to install the beta on my pi.

**Comment by bryce-seifert** [comment]
I don't personally use a Pi, but you may be able to run

`sudo companion-update beta`
Or possibly just

`sudo companion-update` and then select the beta version. Sorry I'm unable to test this.

**Pull request merged**
