### PR TITLE
Feat: Custom presets

### PR DESCRIPTION
**Pull request by CoastIT**
Hi all,

first of all thank you to all who have contributed to this product. This is my first pull request ever, so let me know when I'm doing something wrong.

This feature is to allow a user to integrate his own custom presets to improve the time required to build project specific button pages without having to manually adapt anything on the buttons.

Tested with the latest companion master (2.2.0) on Windows.

Custom_Presets_01

Custom_Presets_02

Custom_Presets_03

Custom_Presets_04

Custom_Presets_05

### CODE REVIEW

**Comment by bryce-seifert** [comment]
My own thinking is it would be better to expand the current preset offering natively, instead of trying to separate this out into a local file, as that feels more user-friendly and less error-prone.

I don't know of another module that does something like this with presets, so definitely need to look into this more.

**Comment by CoastIT** [comment]
Thanks, i had the same thoughts but ended up doing it this way as for me this is my killer feature. I aggree that this would be for experienced user only and there is a risk to break things with the wrong preset file. However, i definetely would have to further do my own builds of companion (would be nice if in the future modules could be added/activated to companion in a dynamic way) when i do not have it in some way. I don't think that it would make sense to offer further predefined presets as everybody would have his own preferences with regard to colors and style and you simply cannot make everybody happy with hardcoded presets. And a better more error prone interface for such stuff would probably be huge effort and a bit overkill. I'll keep thinking on this.

**Comment by bryce-seifert** [comment]
@CoastIT After talking with some other devs about it, the consensus is that instead of every module trying to implement something like this in a variety of ways it would be better to handle custom presets at the core level.

Based on this, I opened this feature request here: https://github.com/bitfocus/companion/issues/1924

Please feel free to take a look at that, add to that discussion based on your thoughts about how this would work

**Comment by CoastIT** [comment]
@bryce-seifert Thank you very much for taking care of it. Have you noticed that my example presets are dynamic? It's like for each scene, for each source, for each source of a specific scene ... and also with some conditions which i think only the obs module is aware of. Not sure if this would be possible on the core level. The idea behind that is to prepare obs for an project and then just move all the wanted buttons from the presets to the page. This would just take seconds to prepare the page and minimize the risk of making mistakes.
But your concerns are justified i think. I just do not have a better idea to implement it in another way while keeping the same flexibility.

**Comment by bryce-seifert** [comment]
Yeah, that all makes sense. I've raised that point on that request as well. I do think iterating through things like scenes applies to other modules as well, but I also don't have any good ideas right now, going to think on it more.

**Comment by bryce-seifert** [comment]
Going to close this, as I think it should be addressed by Companion as a whole, and we have the open feature request which can be tracked here: https://github.com/bitfocus/companion/issues/1924

**Pull request closed without merging**
