### PR TITLE
Feat: Add variables for media time remaining, elapsed

### PR DESCRIPTION
**Pull request by bryce-seifert**
Add media time elapsed, remaining variables (Closes https://github.com/bitfocus/companion-module-obs-studio/issues/119)
Add image file name variable (Closes https://github.com/bitfocus/companion-module-obs-studio/issues/123)

### CODE REVIEW

**Comment by nacalai** [comment]
I find it strange it hasn't been added to the newest versions yet. Any idea why? We'd like to implement this asap :)

**Comment by bryce-seifert** [comment]
@nacalai A lot of the core devs have been busy lately. It's not just OBS, there's a lot of waiting modules.

Are you on Mac? I could make a build for you if so

**Comment by nacalai** [comment]
> @nacalai A lot of the core devs have been busy lately. It's not just OBS, there's a lot of waiting modules.
> 
> Are you on Mac? I could make a build for you if so

Running Windows :) That's kind of you. Would be nice to use it on monday

**Comment by bryce-seifert** [comment]
@nacalai Well looks like it's in the core now :) Let me know how testing goes!

**Comment by kjetilpp** [comment]
How to update only this module? Running PI :)

**Comment by bryce-seifert** [comment]
You are not able to update single modules in companion at this time, only the whole software. Here's the [relevant issue](https://github.com/bitfocus/companion/issues/1002).

**Comment by estilles** [comment]
> You are not able to update single modules in companion at this time, only the whole software. Here's the [relevant issue](https://github.com/bitfocus/companion/issues/1002).

Hey @bryce-seifert, I use a workaround on the Raspberry Pi when I want to test a module that I've updated that has no yet been updated in the Companion core.

- Clone the module repo into the `module-local-dev` folder within companion
- Change into that folder, run `yarn` to install any dependencies
- Restart Companion

For example:
```
cd ~/companion/module-local-dev/
git clone https://github.com/bitfocus/companion-module-obs-studio.git
cd companion-module-obs-studio
yarn
sudo systemctl restart companion
```

**Comment by krocheck** [comment]
Easier option is to edit the root `package.json`, find the dependency for `companion-module-obs-studio`, update the tag at the end of the line to the new version, then run a `yarn` for it to apply that update.

**Comment by kjetilpp** [comment]
@estilles Nice, did not know about module-local-dev. So helpful to use that folder, will save me a lot of time, thanks!😄

**Comment by estilles** [comment]
> @estilles Nice, did not know about module-local-dev. So helpful to use that folder, will save me a lot of time, thanks!😄 

Thanks @kjetilpp. @krocheck's suggestion is really good too.

**Pull request merged**
