### PR TITLE
Add more variables from OBS

### PR DESCRIPTION
**Pull request by eric**
I found these variables to be useful.

### CODE REVIEW

**Comment by krocheck** [comment]
@eric my only question here is related to your inline function `roundIfDefined `.  It's placed in the code twice, so I question if that should be moved to `instance.prototype.` and calls addressed to `self.`?

**Comment by eric** [comment]
Yeah, that’s a good call. I’ll fix it.

**Comment by eric** [comment]
I've fixed it

**Comment by krocheck** [comment]
perf.  thanks!

**Pull request merged**
