### PR TITLE
Feat: All sources for toggle_scene_item action

### PR DESCRIPTION
**Pull request by CoastIT**
This feature adds "all sources" to the "Set Source Visibility" action

All_Sources_for_Toggle_Scene_Item_ Action_01
.

### CODE REVIEW

**Comment by bryce-seifert** [comment]
This seems to work reliably for True/ False, but I'm having some issues with the Toggle option.

For me the Toggle is only working on nested scenes, not any other sources in a scene. I did a quick glance and I'm not immediately sure why, but I can take a closer look later this week

**Comment by CoastIT** [comment]
Thanks, I'll also check again. I may have not done enough testing on the toggle use case after my last changes :-( as this was not my main use case.

**Comment by CoastIT** [comment]
Indeed I broke the toggle use case for child sources (is it this what you've found as well?), but I think I've found the problem.

I've changed the original code a bit because I thought the iteration over the sources might not be required to lookup a source in self.sources. 

In the self.sources data structure there is a 
	self.sources['group child source name']
as well as a 
	self.sources['group name'].groupChildren['group child source name']

I took the wrong one (the first one) but this one is not reflecting all values of the source, e.g .render property is not included there (as i would expect).

However, I'll fix it and provide another commit.
Or do you think this could be treated as a problem in updateScenesAndSources() and it should be fixed there? It's probaly not a matter of right or wrong but more of what is expected in self.sources['group child scene name'].

**Comment by CoastIT** [comment]
I think I've fixed it, many thanks to bryce-seifert to point that out. I need to do some more testing. Is still wonder what would be the best way to deal with the source groups. I currently don't touch them for the "ALL SCENES" use case, but only the group members.

What I'm also not completely sure is if it's ok do do multiple obs.send whereas the handle.catch is just at the end of the function. Should I add a handle.catch also in the loop where I do the obs.send?

**Comment by bryce-seifert** [comment]
It looks like it's toggling correctly now for all sources! 
Although, there is one thing (related to the handle.catch I think). If you try to run the action when you pick a source that is not in the scene you picked, it throws a `Error executing action: Cannot read property 'catch' of undefined`

I think how you've done groups is fine, since all the sources in the group are going to be affected anyways

**Comment by CoastIT** [comment]
Thank you very much for the review.

With that same use case 1.0.31 throws a warning: ```specified scene item doesn't exist```

My new code prevents that warning because obs.send SetSceneItemProperties is not fired in that case.
But i think that's ok because we don't have to call out to obs in that case anyway. Am I right on this?

To fix the case where the action is not supposed to do anything I've just wrapped the handle.catch in an if (handle){} block.

**Pull request merged**
